name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main # o "master", si es tu rama principal

jobs:
  deploy:
    name: Build and Deploy Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: functions

      - name: Build TypeScript
        run: npm run build
        working-directory: functions

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
